fixtures:
  repositories:
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    owncloud: "#{source_dir}"
